package model

type RegistroECF struct {
	Seq         int    `json:"seq"`
	Campo       string `json:"campo"`
	Descricao   string `json:"descricao"`
	Tipo        string `json:"tipo"`
	Bytes       int    `json:"bytes"`
	Observacoes string `json:"observacoes"`
}

func GetEcf(fields []string) []RegistroECF {
	return []RegistroECF{
		{
			Seq:         1,
			Campo:       "TIPO",
			Descricao:   "Tipo de registro, valor fixo.",
			Tipo:        "A",
			Bytes:       3,
			Observacoes: "Fixo ECF",
		},
		{
			Seq:         2,
			Campo:       "CODLOJA",
			Descricao:   "Código da loja no DJMonitor.",
			Tipo:        "N",
			Bytes:       4,
			Observacoes: "",
		},
		{
			Seq:         3,
			Campo:       "CODTERMINAL",
			Descricao:   "Código do terminal no DJMonitor.",
			Tipo:        "N",
			Bytes:       4,
			Observacoes: "",
		},
		{
			Seq:         4,
			Campo:       "CODTERMINALEXT",
			Descricao:   "Código do terminal utilizado na aplicação de retaguarda",
			Tipo:        "AN",
			Bytes:       10,
			Observacoes: "",
		},
		{
			Seq:         5,
			Campo:       "CODECF",
			Descricao:   "Código do ECF no DJ Monitor.",
			Tipo:        "N",
			Bytes:       4,
			Observacoes: "",
		},
		{
			Seq:         6,
			Campo:       "NUM ECF",
			Descricao:   "Número sequencial do ECF dentro da empresa.",
			Tipo:        "N",
			Bytes:       4,
			Observacoes: "",
		},
		{
			Seq:         7,
			Campo:       "NUM LOJA",
			Descricao:   "Número da loja gravado no ECF.",
			Tipo:        "N",
			Bytes:       4,
			Observacoes: "",
		},
		{
			Seq:         8,
			Campo:       "NUM USUARIO",
			Descricao:   "Número do usuário atual cadastrado no ECF.",
			Tipo:        "N",
			Bytes:       4,
			Observacoes: "",
		},
		{
			Seq:         9,
			Campo:       "CRO",
			Descricao:   "Contador de Reinicio de Operações.",
			Tipo:        "N",
			Bytes:       4,
			Observacoes: "",
		},
		{
			Seq:         10,
			Campo:       "MF ADICIONAL",
			Descricao:   "Letra indicativa da memória adicional.",
			Tipo:        "A",
			Bytes:       1,
			Observacoes: "Ver nota 1.",
		},
		{
			Seq:         11,
			Campo:       "MARCA",
			Descricao:   "Marca do ECF.",
			Tipo:        "A",
			Bytes:       1,
			Observacoes: "Ver nota 2.",
		},
		{
			Seq:         12,
			Campo:       "CNIECF",
			Descricao:   "Código Nacional de Identificação do ECF",
			Tipo:        "A",
			Bytes:       6,
			Observacoes: "Ver nota 3.",
		},
		{
			Seq:         13,
			Campo:       "VERSAOSB",
			Descricao:   "Versão do Software Básico.",
			Tipo:        "A",
			Bytes:       10,
			Observacoes: "",
		},
		{
			Seq:         14,
			Campo:       "DATASB",
			Descricao:   "Data de gravação do Software Básico.",
			Tipo:        "D",
			Bytes:       8,
			Observacoes: "",
		},
		{
			Seq:         15,
			Campo:       "HORASB",
			Descricao:   "Hora de gravação do Software Básico.",
			Tipo:        "H",
			Bytes:       6,
			Observacoes: "",
		},
		{
			Seq:         16,
			Campo:       "CODEXTERNO",
			Descricao:   "Código externo do ECF utilizado pela aplicação de retaguarda.",
			Tipo:        "A",
			Bytes:       10,
			Observacoes: "",
		},
		{
			Seq:         17,
			Campo:       "DATA CADUSUARIO",
			Descricao:   "Data do cadastro do usuário atual.",
			Tipo:        "D",
			Bytes:       8,
			Observacoes: "",
		},
		{
			Seq:         18,
			Campo:       "HORA CADUSUARIO",
			Descricao:   "Hora do cadastrado do usuário atual.",
			Tipo:        "H",
			Bytes:       6,
			Observacoes: "",
		},
		{
			Seq:         19,
			Campo:       "DECIMAIS QTD",
			Descricao:   "Número máximo de casas decimais permitidas para quantidade.",
			Tipo:        "N",
			Bytes:       1,
			Observacoes: "Ver nota 4.",
		},
		{
			Seq:         20,
			Campo:       "DECIMAIS PRECO",
			Descricao:   "Número máximo de casas decimais permitidas para o preço unitário.",
			Tipo:        "N",
			Bytes:       1,
			Observacoes: "Ver nota 5.",
		},
		{
			Seq:         21,
			Campo:       "ARREDONDA",
			Descricao:   "Flag indicando se o ECF faz arredondamento.",
			Tipo:        "A",
			Bytes:       1,
			Observacoes: "Ver nota 6.",
		},
		{
			Seq:         22,
			Campo:       "NUMERO_SERIE",
			Descricao:   "Número de série do ECF.",
			Tipo:        "AN",
			Bytes:       30,
			Observacoes: "",
		},
	}
}
